apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: simple-sidecar.tanzu.vmware.com
  namespace: default
spec:
  buildpacks:
    builderName: base-jammy-offline.tanzu.vmware.com
  postBuildSteps:
  - namedTask: containerapp-defaults.tanzu.vmware.com
  - namedTask: spring-boot.tanzu.vmware.com
  runtimes:
  - description: create a carvel package for deploying on kubernetes
    name: kubernetes-carvel-package
    steps:
    - namedTask: kubernetes-deployment.tanzu.vmware.com
    - containerTask:
        command:
          - /script/docker-script.sh
        image: ghcr.io/mhoshi-vm/tanzu-build-add-sidecar@sha256:34c957e4978a744f39b1cc202f20166ad6e2485cffcbc4a47d03f5a91a699a7f
    - namedTask: kubernetes-carvel-package.tanzu.vmware.com
