apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: simple-sidecar.tanzu.vmware.com
  namespace: default
spec:
  buildpacks:
    builderName: base-jammy-offline.tanzu.vmware.com
  postBuildSteps:
  - namedTask: containerapp-defaults.tanzu.vmware.com
  - namedTask: spring-boot.tanzu.vmware.com
  runtimes:
  - description: create a carvel package for deploying on kubernetes
    name: kubernetes-carvel-package
    steps:
    - namedTask: kubernetes-deployment.tanzu.vmware.com
    - containerTask:
        image: bitnami/git
        command:
          - /bin/sh
          - -c
        args:
          - |
            git clone https://github.com/mhoshi-vm/tanzu-build-add-sidecar.git kustomize ;
            chmod -R 777 kustomize/* kustomize/.*
    - containerTask:
        image: line/kubectl-kustomize
        command: [ "kustomize" ]
        args:
        - build
        - "--load-restrictor"
        - LoadRestrictionsNone
        - kustomize
        - "-o"
        - output/app-config/deployment.yml
    - namedTask: kubernetes-carvel-package.tanzu.vmware.com
